name = "local-ai-landing"
main = "src/index.js"
compatibility_date = "2024-01-29"

# Configure the custom domain
routes = [
	{ pattern = "localai.alert24.org", custom_domain = true }
]

[assets]
directory = "./public"
binding = "ASSETS"
